version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - skip: true

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Performance Improvements'
      regexp: "^.*perf[(\\w)]*:+.*$"
      order: 2
    - title: 'Dependency Updates'
      regexp: "^.*build\\(deps\\):+.*$"
      order: 3
    - title: 'Other Changes'
      order: 999

release:
  github:
    owner: Prescott-Data
    name: dromos-authkit

  name_template: "Release {{.Tag}}"

  header: |
    ## Dromos AuthKit {{.Tag}}

    Authentication and authorization middleware for Gin applications.

    ### Installation

    ```bash
    go get github.com/Prescott-Data/dromos-authkit@{{.Tag}}
    ```

  footer: |
    **Full Changelog**: https://github.com/Prescott-Data/dromos-authkit/compare/{{.PreviousTag}}...{{.Tag}}

snapshot:
  version_template: "{{ incpatch .Version }}-next"
